name: LuxMed Slot Checker

on:
  schedule:
    # --- פרופיל שעון קיץ (מרץ עד אוקטובר) ---
    - cron: '30,40,50 3 * 3-10 *'
    - cron: '*/10 4-19 * 3-10 *'
    - cron: '0 20 * 3-10 *'
    # --- פרופיל שעון חורף (נובמבר עד מרץ) ---
    - cron: '30,40,50 4 * 11,12,1,2 *'
    - cron: '*/10 5-20 * 11,12,1,2 *'
    - cron: '0 21 * 11,12,1,2 *'

  workflow_dispatch:

jobs:
  check_slots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        echo "Installing base requirements..."
        pip install -r requirements.txt
        echo "Installing telegram dependency..."
        pip install telegram-send

    - name: Create Configuration File
      run: |
        cat <<EOF > config.yml
        luxmed:
          login: "${{ secrets.LUXMED_LOGIN }}"
          password: "${{ secrets.LUXMED_PASSWORD }}"
        luxmedsniper:
          notification_provider: "telegram"
          doctor_locators:
            - id: "${{ secrets.DOCTOR_ID }}"
              name: "Target Doctor Search"
              enabled: True
          lookup_time_days: 2
        telegram:
          token: "${{ secrets.TELEGRAM_TOKEN }}"
          chat_id: "${{ secrets.TELEGRAM_CHAT_ID }}"
          message_template: "New visit! {AppointmentDate} at {ClinicPublicName} - {DoctorName}"
        misc:
          notifydb: ./notifications.db
        EOF

    - name: Run Luxmed Sniper
      run: |
        python3 luxmed_sniper.py -c config.yml &
        sleep 60
        kill $!
